name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [github.com/aquilax/mbox-tools/lib/mbox, github.com/aquilax/mbox-tools/cmd/mbox-tools]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build ${{ matrix.package }}
      run: go build -v ${{ matrix.package }}

    - name: Test ${{ matrix.package }}
      run: go test -v ${{ matrix.package }}
